
#markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
#kramdown:	
#input: GFM

#excerpt_separator: <!--more-->
#highlighter: rouge

#safe: true
#lsi: false

exclude: ["*.Rmd"]
name: Grace Smith Vidaurre
